@feature/next.js
trilogy-group/tu2k22-openchakra pull request #1
Opened 2022-09-26 18:18 UTC by ayodeji-ti

2022-09-26 18:19 UTC, ayodeji-ti commented
Next.js now handles the code sync, not express.js, hence there is only one server running, [loom video](https://www.loom.com/share/d0d160c439a946d9bc07987a4b85579d)

2022-10-01 07:44 UTC, vinayak-sachdeva commented on next.config.js
> +const nextConfig = {}
don't we need this config now?

2022-10-01 07:45 UTC, vinayak-sachdeva commented on package.json
> +  "version": "1.0.6",
version it 0.0.x until first release

2022-10-01 07:48 UTC, vinayak-sachdeva commented on src/components/CodePanel.tsx
> +    baseURL: `${window.location.href}api`,
Inelegant, what if it doesn't end with '/', please find some alternate solution

2022-10-01 07:48 UTC, vinayak-sachdeva commented on src/components/CodePanel.tsx
> +    baseURL: `${window.location.href}api`,
can you try localhost:3003

2022-10-01 08:48 UTC, vinayak-sachdeva requested changes
Please address all the comments

2022-10-01 13:13 UTC, ayodeji-ti commented on package.json
> +  "version": "1.0.6",
okay

2022-10-01 15:40 UTC, merged