Fix/loop
trilogy-group/tu2k22-openchakra pull request #29
Opened 2022-11-20 23:14 UTC by ayodeji-ti

Instead of the number of times the element being displayed in the loop to depend on the value of the list passed to it, the user can instead specify how many times the it is to be displayed.
![Screenshot (414)](https://user-images.githubusercontent.com/99248255/202931690-971e11c3-7839-4b31-abb3-e773115ceaa0.png)

2022-11-20 23:16 UTC, ayodeji-ti commented
This fixes the bug with the looped view, while also giving the user the ability to change the number, if the value entered is not a number or is 0, then the element is shown 4 times

2022-11-21 11:14 UTC, vinayak-sachdeva requested changes
Looks incomplete, how will it impact code generation

2022-11-21 11:38 UTC, ayodeji-ti commented
It's not supposed to impact code generation at all, similar to the conditional component where show both, show false etc doesn't impact the code

2022-11-21 12:03 UTC, vinayak-sachdeva commented
> It's not supposed to impact code generation at all, similar to the conditional component where show both, show false etc doesn't impact the code

Then from where will you get the list value in code. Create a sample component using loop and share its generated code

2022-11-30 11:33 UTC, ayodeji-ti commented
![Screenshot (473)](https://user-images.githubusercontent.com/99248255/204785598-0eb38b60-8a6b-4bb2-949f-04e18d324d85.png)


```
import React, { RefObject } from 'react'
import { ChakraProvider, Box, Button } from '@chakra-ui/react'

const App = () => (
  <ChakraProvider resetCSS>
    {['Hello', 'HI', 'Sup'].map((itemMAD, indexMAD) => (
      <Box>
        <Button variant="solid" size="md">
          {itemMAD}
        </Button>
      </Box>
    ))}
  </ChakraProvider>
)

export default App
```

2023-01-29 13:37 UTC, closed without merging